WINGS_DATE_YEAR := $(shell date -u +%Y)
WINGS_DATE_MONTH := $(shell date -u +%m)
WINGS_DATE_DAY := $(shell date -u +%d)
WINGS_DATE_HOUR := $(shell date -u +%H)
WINGS_DATE_MINUTE := $(shell date -u +%M)
WINGS_BUILD_DATE_UTC := $(shell date -d '$(WINGS_DATE_YEAR)-$(WINGS_DATE_MONTH)-$(WINGS_DATE_DAY) $(WINGS_DATE_HOUR):$(WINGS_DATE_MINUTE) UTC' +%s)
WINGS_BUILD_DATE := $(WINGS_DATE_YEAR)$(WINGS_DATE_MONTH)$(WINGS_DATE_DAY)-$(WINGS_DATE_HOUR)$(WINGS_DATE_MINUTE)

WINGS_PLATFORM_VERSION := 14.0

WINGS_VERSION := WingsOS-$(WINGS_BUILD)-$(WINGS_PLATFORM_VERSION)-$(WINGS_BUILD_DATE)
WINGS_VERSION_PROP := fourteen
